FROM jenkins/inbound-agent

USER root

# python
RUN apt-get update && apt-get install -y \
        python3 \
        python3-pip \
        python-setuptools \
    && rm -rf /var/lib/apt/lists/*

# pypi based packages
RUN pip3 install -U \
        pip \
        setuptools

# docker
COPY setup_docker.sh /tmp/
RUN bash /tmp/setup_docker.sh \
    && rm -f /tmp/setup_docker.sh

ARG uid=1000
ARG gid=1000

RUN groupadd -g ${gid} ${gid} || true
RUN usermod -u ${uid} jenkins \
    && usermod -g ${gid} jenkins

# Note. not a clean solution but may help to
#       adjust user system records if needed
#       (e.g. for python pwd.getpwuid(<uid>))
# RUN userdel jenkins
# RUN useradd -c "Jenkins user" -u 728015 -g 728015 jenkins

ARG docker_gid=999

RUN (groupadd docker || true) \
    && groupmod -g ${docker_gid} docker


RUN usermod -aG docker jenkins

USER jenkins
