#
# Copyright (c) 2020 Seagate Technology LLC and/or its Affiliates
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published
# by the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU Affero General Public License for more details.
# You should have received a copy of the GNU Affero General Public License
# along with this program. If not, see <https://www.gnu.org/licenses/>.
# For any questions about this software or licensing,
# please email opensource@seagate.com or cortx-questions@seagate.com.
#

FROM jenkins/inbound-agent

USER root

# python
RUN apt-get update && apt-get install -y \
        python3 \
        python3-pip \
        python-setuptools \
    && rm -rf /var/lib/apt/lists/*

# pypi based packages
RUN pip3 install -U \
        pip \
        setuptools

# docker
COPY setup_docker.sh /tmp/
RUN bash /tmp/setup_docker.sh \
    && rm -f /tmp/setup_docker.sh

ARG uid=1000
ARG gid=1000

RUN groupadd -g ${gid} ${gid} || true
RUN usermod -u ${uid} jenkins \
    && usermod -g ${gid} jenkins

# Note. not a clean solution but may help to
#       adjust user system records if needed
#       (e.g. for python pwd.getpwuid(<uid>))
# RUN userdel jenkins
# RUN useradd -c "Jenkins user" -u 728015 -g 728015 jenkins

ARG docker_gid=999

RUN (groupadd docker || true) \
    && groupmod -g ${docker_gid} docker


RUN usermod -aG docker jenkins

USER jenkins
