FROM jenkins/inbound-agent

USER root

# python
RUN apt-get update && apt-get install -y \
        python3 \
        python3-pip \
        python-setuptools \
    && rm -rf /var/lib/apt/lists/*

# pypi based packages
RUN pip3 install -U \
        pip \
        setuptools

# docker
COPY setup_docker.sh /tmp/
RUN bash /tmp/setup_docker.sh \
    && rm -f /tmp/setup_docker.sh

ARG uid=1000
ARG gid=1000

RUN usermod -u ${uid} jenkins \
    && usermod -g ${gid} jenkins

RUN usermod -aG docker jenkins

USER jenkins
