#!/usr/bin/env groovy

node {
    properties([
        buildDiscarder(logRotator(artifactDaysToKeepStr: '', artifactNumToKeepStr: '', daysToKeepStr: '5', numToKeepStr: '5')),
        parameters([
            string(defaultValue: '', description: 'FQDN of VM to deploy on.', name: 'HOST_NAME', trim: true),
            string(defaultValue: '', description: '''Build having following directory structure:
                3rd_party/
                cortx_iso/
                iso/
                python_deps/
                README.txt
                RELEASE.INFO
                THIRD_PARTY_RELEASE.INFO''', name: 'BUILD_URL', trim: true),
            password(description: 'root user password for the target node.', name: 'PASSWORD')
        ])
    ])

    def remote = [:]
    withEnv(["CORTX_RELEASE_REPO=${BUILD_URL}","SSHPASS=${PASSWORD}"]) {
        ansiColor('xterm') {
            remote.name = "srvnode-1"
            remote.host = HOST_NAME
            remote.user = 'root'
            remote.password = PASSWORD
            remote.allowAnyHosts = true

            stage("SSH Connectivity Check") {
                if (PASSWORD.isEmpty()) {
                    error "Target VM password cannot be empty."
                }
                
                sshCommand remote: remote, command: "exit"
                echo "Successfully connected to VM ${HOST_NAME}!"
            }
            
            stage("Build URL Check") {
                sh label: '', returnStatus: true, script: 'test 200 == $(curl -ksI ${BUILD_URL}/RELEASE.INFO|grep "HTTP/1.1" | cut -d " " -f 2)'
            }
            
            stage("Storage Configuration Check") {
                try { 
                    sshCommand remote: remote, command: """
                        test 2 == \$(lsblk -d|grep -E 'sdb|sdc'|wc -l)
                    """
                    echo "The VM has exactly 2 nos. of attached disks. Check Successful!"
                } catch(Exception ex) {
                    error 'The VM should have exactly 2 attached disks. Kindly provide a VM with exactly 2 attached disks.'
                }
            }
            
            stage("Prepare config.ini") {
                sshCommand remote: remote, command: "curl -O https://gist.githubusercontent.com/ypise/d2949b8c0e28db50c8ac670beebbf3f6/raw/3a2d97558d9da7c57dfda658b227ee156eeb6059/config.ini -o /root/config.ini"
                sshCommand remote: remote, command: "sed -i 's/\${HOST_NAME}/${HOST_NAME}/g' /root/config.ini"
                echo "Successfully created config.ini file!"
            }
            
            stage("Install Provisioner API") {
                sshCommand remote: remote, command: """
                    yum install -y yum-utils
                    yum-config-manager --add-repo "${CORTX_RELEASE_REPO}/3rd_party/"
                    yum install --nogpgcheck -y python3 python36-m2crypto salt salt-master salt-minion
                    rm -rf /etc/yum.repos.d/*3rd_party*.repo
                    yum-config-manager --add-repo "${CORTX_RELEASE_REPO}/cortx_iso/"
                    yum install --nogpgcheck -y python36-cortx-prvsnr
                    rm -rf /etc/yum.repos.d/*cortx_iso*.repo
                    yum clean all
                    rm -rf /var/cache/yum/
                    provisioner --version
                """
                echo "Successfully installed Provisioner API!"
            }
            
            stage("Bootstrap Provisioner") {
                sshCommand remote: remote, command: """
                    yum install -y sshpass
                    sshpass -p $PASSWORD provisioner setup_provisioner srvnode-1:\$(hostname -f) --logfile --logfile-filename /var/log/seagate/provisioner/setup.log --source rpm --config-path ~/config.ini --dist-type bundle --target-build ${CORTX_RELEASE_REPO}
                    provisioner configure_setup /root/config.ini 1
                    salt-call state.apply components.system.config.pillar_encrypt
                    provisioner pillar_export
                """
                echo "Successfully bootstrapped provisioner!"
            }
            
            stage("Validate Bootstrap Provisioner") {
                sshCommand remote: remote, command: """
                    salt '*' test.ping
                    salt "*" service.stop puppet
                    salt "*" service.disable puppet
                    salt '*' pillar.get release
                    salt '*' grains.get node_id
                    salt '*' grains.get cluster_id
                    salt '*' grains.get roles
                """
                echo "Successfully validated bootstrap!"
            }
            
            stage("Platform Setup") {
                sshCommand remote: remote, command: "provisioner deploy_vm --states system --setup-type single"
                echo "Successfully deployed system states!"
            }
            
            stage("3rd Party Software Deployment") {
                sshCommand remote: remote, command: "provisioner deploy_vm --states prereq --setup-type single"
                echo "Successfully deployed prereq states!"
            }
            
            catchError {
                stage("Data Path States Deployment") {
                    // timeout(30) {
                    //     input 'Proceed with Data Path Stage?'
                    // }
                    sshCommand remote: remote, command: "provisioner deploy_vm --states iopath --setup-type single"
                    echo "Successfully deployed iopath states!"
                }
            }
            
            stage("Control Stack States Deployment") {
                // timeout(30) {
                //     input 'Proceed with Control Path Stage?'
                // }
                sshCommand remote: remote, command: "provisioner deploy_vm --states controlpath --setup-type single"
                echo "Successfully deployed controlpath states!"
            }
            
            stage("HA States Deployment") {
                // timeout(30) {
                //     input 'Proceed with HA Setup Stage?'
                // }
                sshCommand remote: remote, command: "provisioner deploy_vm --states ha --setup-type single"
                echo "Successfully deployed HA states!"
            }
        }

        sshGet remote: remote, from: '/opt/seagate/cortx_configs/provisioner_cluster.json', into: 'archives/provisioner_cluster.json', override: true
        sshGet remote: remote, from: '/var/log/seagate/provisioner/setup.log', into: 'archives/setup.log', override: true
        archiveArtifacts artifacts: 'archives/provisioner_cluster.json,archives/setup.log', followSymlinks: false
    }
}

