#!/usr/bin/bash
#
# Copyright (c) 2020 Seagate Technology LLC and/or its Affiliates
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published
# by the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU Affero General Public License for more details.
# You should have received a copy of the GNU Affero General Public License
# along with this program. If not, see <https://www.gnu.org/licenses/>.
# For any questions about this software or licensing,
# please email opensource@seagate.com or cortx-questions@seagate.com.
#


set -euE

export LOG_FILE="${LOG_FILE:-/var/log/seagate/provisioner/unboxing_nw_bmc.log}"
mkdir -p $(dirname "${LOG_FILE}")
#truncate -s 0 ${LOG_FILE}


# Set BMC dhcp network configs
function set_bmc_dhcp_config {

    for remote in ${remotes[@]}; do
        _linfo "================================================================================"
        _linfo "Setting BMC Network Information for DHCP on ${remote}"
        _linfo "================================================================================"

        remote_execute ${remote} "ipmitool lan set 1 ipsrc dhcp"
        remote_execute ${remote} "ipmitool lan set 1 access on"
        _linfo "Sleeping for 30 secs for the settings to take effect"
        remote_execute ${remote} "sleep 30"

        _linfo "********************************************************************************"
        _linfo "BMC LAN settings have been updated to: "
        _linfo "********************************************************************************"
        remote_execute ${remote} "ipmitool lan print 1"
        _linfo "********************************************************************************"
    done

    _linfo "================================================================================"
    _linfo "        "

    proceed_check
}


# Set BMC static network configs
function set_bmc_static_config {

    _linfo "================================================================================"
    _linfo "Setting BMC Network Information for Static IP"
    _linfo "================================================================================"
    
    read -p "BMC IP for Server-A: " bmc_srv_1
    read -p "BMC IP for Server-B: " bmc_srv_2
    read -p "Gateway IP for BMC interfaces on both nodes: " gw_ip
    read -p "Netmask for BMC network on both servers [255.255.255.0]: " netmask
    [[ -z ${netmask} ]] && netmask=255.255.255.0

    while true; do
        _linfo "********************************************************************************"
        _linfo "You have provided the following information:"
        _linfo "    BMC IP for Server-A:                       ${mgmt_ip_1}"
        _linfo "    BMC IP for Server-B:                       ${mgmt_ip_2}"
        _linfo "    Gateway IP for BMC interfaces on both nodes:    ${gw_ip}"
        _linfo "    Netmask for BMC network on both servers:        ${netmask}"
        _linfo "********************************************************************************"
        _linfo "    "
        read -n1 -p "Given the above information,
          do you wish to proceed with Static IP based NW configuration
          for BMC interfaces?(y/n): " _ans

        case $_ans in
            [Yy]* ) break;;
            [Nn]* ) exit 10;;
            * ) echo "Please answer y or n.";;
        esac
    done

    local node_name=null
    for remote in ${remotes[@]}; do
        _linfo "Setting BMC Network Information for Static IP on ${remote}"
        remote_execute ${remote} "ipmitool lan set 1 ipsrc static"
        
        if [[ -n ${bmc_srv_1} ]]; then
            # BMC settings update for node-1
            node_name=srvnode-1
            remote_execute ${remote} "ipmitool lan set 1 ipaddr ${bmc_srv_1}"
        elif [[ -n ${bmc_srv_2} ]]; then
            # BMC settings update for node-2
            node_name=srvnode-2
            remote_execute ${remote} "ipmitool lan set 1 ipaddr ${bmc_srv_2}"
        else
            # This should never be hit
            _lerror "This should never be seen. If you see this, there is something unexpected heppening."
            exit 23
        fi

        remote_execute ${remote} "ipmitool lan set 1 defgw ipaddr ${gw_ip}"
        remote_execute ${remote} "ipmitool lan set 1 netmask ${netmask}"
        # ipmitool lan set 1 arp respond on
        remote_execute ${remote} "ipmitool lan set 1 access on"

        _linfo "Sleeping for 30 secs for the settings to take effect"
        remote_execute ${remote} "sleep 30"

        _linfo "********************************************************************************"
        _linfo "BMC LAN settings on ${node_name} have been updated to: "
        _linfo "********************************************************************************"
        remote_execute ${remote} "ipmitool lan print 1"
        _linfo "********************************************************************************"
        
    done

    _linfo "================================================================================"
    _linfo "        "

    proceed_check
}
