#!/usr/bin/env groovy

def remote = [:]
remote.name = "srvnode-1"
remote.host = HOST_NAME
remote.user = 'root'
remote.password = PASSWORD
remote.allowAnyHosts = true

node {
    withEnv(["SSHPASS=${PASSWORD}"]) {
        ansiColor('xterm') {
            stage("SSH Connectivity Check") {
                sshCommand remote: remote, command: "exit"
                echo "Successfully connected to VM ${HOST_NAME}!"
            }

            stage("Teardown of Cortx Stack!") {
                sshCommand remote: remote, command: """
                    /opt/seagate/cortx/provisioner/cli/destroy-vm --ctrlpath-states --iopath-states --prereq-states --system-states --ha-states || true
                """
                echo "Successfully teardown of Cortx Stack!"
            }

            stage("Stop Salt services") {
                sshCommand remote: remote, command: """
                    #systemctl stop glustersharedstorage glusterfsd glusterd
                    systemctl stop salt-minion salt-master || true
                """
                echo "Sucessfully stopped salt and gluster services"
            }            
            stage("Uninstall rpms") {
                sshCommand remote: remote, command: """
                    yum erase -y cortx-prvsnr cortx-prvsnr-cli      # Cortx Provisioner packages
                    yum erase -y gluster-fuse gluster-server        # Gluster FS packages
                    yum erase -y salt-minion salt-master salt-api   # Salt packages
                    yum erase -y python36-m2crypto                  # Salt dependency
                    yum erase -y python36-cortx-prvsnr              # Cortx Provisioner API packages
                    yum autoremove -y
                    yum clean all
                    rm -rf /var/cache/yum
                    # Remove cortx-py-utils
                    pip3 uninstall -y cortx-py-utils
                    # Cleanup pip packages
                    pip3 freeze|xargs pip3 uninstall -y
                    # Cleanup pip config
                    test -e /etc/pip.conf && rm -f /etc/pip.conf
                    rm -rf ~/.cache/pip
                """
                echo "Successfully uninstalled rpms"
            }
            stage("Cleanup bricks and other directories") {
                sshCommand remote: remote, command: """
                    # Cortx software dirs
                    rm -rf /opt/seagate/cortx || true
                    rm -rf /opt/seagate/cortx_configs || true
                    rm -rf /opt/seagate || true
                    # Bricks cleanup
                    test -e /var/lib/seagate && rm -rf /var/lib/seagate
                    test -e /srv/glusterfs && rm -rf /srv/glusterfs
                    # Cleanup Salt
                    test -e /var/cache/salt && rm -rf /var/cache/salt
                    test -e /etc/salt && rm -rf /etc/salt
                    # Cleanup Provisioner profile directory
                    test -e /opt/isos && rm -rf /opt/isos
                    test -e /root/.provisioner && rm -rf /root/.provisioner
                    test -e /root/.ssh && rm -rf /root/.ssh
                """
                echo "Successfully removed!"
            }
        }
        // archiveArtifacts artifacts: '/opt/seagate/cortx_configs/provisioner_cluster.json,/var/log/seagate/provisioner/setup.log', followSymlinks: false
    }
}

