---
- name: Openldap setup for S3 Auth server (not idempotent, only use for fresh setup)
  hosts: s3ldapnode
  remote_user: root
  gather_facts: yes
  vars:
    ldap_url: ldap:\/\/\/ ldaps:\/\/\/ ldapi:\/\/\/
    openldappasswd: seagate
    ldapiamadminpasswd: ldapadmin

  tasks:

      - name: Upgrade selinux-policy to latest (required by openldap)
        yum: pkg=selinux-policy state=latest

      - name: Install Openldap packages
        yum: pkg={{item}} state=installed
        with_items:
          - openldap-servers
          - openldap-clients

      # - name: Install ntp
      #   yum: pkg=ntp state=installed
      #
      # - name: Configure ntp (required for ldap replication)
      #   command: ntpdate time.seagate.com
      #   notify:
      #     - restart ntpd

      - name: Enable slapd service
        command: systemctl enable slapd

      - name: Ensures temp /tmp/s3ldap dir exists
        file: path=/tmp/s3ldap state=directory

      - name: Generate slappasswd for rootDN
        shell: slappasswd -s {{ openldappasswd }}
        register: slapdpasswdhash
        no_log: true

      - name: Copy Initial ldap config using "slapdpasswdhash" above
        template:
          src: files/ldap/cfg_ldap.ldif
          dest: /tmp/s3ldap/cfg_ldap.ldif

      - name: Generate slappasswd for IAM admin
        shell: slappasswd -s {{ ldapiamadminpasswd }}
        register: ldapadminpasswdhash
        no_log: true

      - name: Copy ldap config using "ldapadminpasswdhash" above
        template:
          src: files/ldap/iam-admin.ldif
          dest: /tmp/s3ldap/iam-admin.ldif

      - name: Copy ldap schema, data, replication-config files
        copy: src={{ item.src }} dest={{ item.dest }}
        with_items:
          - { src: 'ldap/cn={1}s3user.ldif', dest: '/tmp/s3ldap/cn={1}s3user.ldif' }
          - { src: 'ldap/ldap-init.ldif', dest: '/tmp/s3ldap/ldap-init.ldif' }
          - { src: 'ldap/iam-admin-access.ldif', dest: '/tmp/s3ldap/iam-admin-access.ldif' }
          - { src: 'ldap/syncprov_mod.ldif', dest: '/tmp/s3ldap/syncprov_mod.ldif' }
          - { src: 'ldap/syncprov.ldif', dest: '/tmp/s3ldap/syncprov.ldif' }

      - name: Clean up old ldap files
        file:
          state: absent
          path: /etc/openldap/slapd.d/cn=config/cn=schema/cn={1}s3user.ldif

      - name: Start slapd
        service:
          name: slapd
          state: restarted
          enabled: yes

      - name: Remove old ldap files
        file:
          name: /etc/openldap/slapd.d/cn\=config/cn\=schema/cn\=\{1\}s3user.ldif
          state: absent

      - name: Configure OpenLDAP - Base config
        command: ldapmodify -Y EXTERNAL -H ldapi:/// -w {{ openldappasswd }} -f /tmp/s3ldap/cfg_ldap.ldif
        no_log: true

      - name: Remove Base ldap config file
        file:
          name: /tmp/s3ldap/cfg_ldap.ldif
          state: absent

      - name: restart slapd
        service:
          name: slapd
          state: restarted

      - name: Configure OpenLDAP - Schema
        command: ldapadd -x -D "cn=admin,cn=config" -w {{ openldappasswd }} -f /tmp/s3ldap/cn={1}s3user.ldif
        no_log: true

      - name: Configure OpenLDAP - Base data
        command: ldapadd -x -D "cn=admin,dc=seagate,dc=com" -w {{ openldappasswd }} -f /tmp/s3ldap/ldap-init.ldif
        no_log: true

      - name: Configure OpenLDAP - Add IAM admin
        command: ldapadd -x -D "cn=admin,dc=seagate,dc=com" -w {{ openldappasswd }} -f /tmp/s3ldap/iam-admin.ldif
        no_log: true

      - name: Configure OpenLDAP - Setup permissions for IAM admin
        command: ldapmodify -Y EXTERNAL -H ldapi:/// -w {{ openldappasswd }} -f /tmp/s3ldap/iam-admin-access.ldif
        no_log: true

      - name: Copy SSL config file for openldap
        copy:
          src: files/ldap/ssl/ssl_certs.ldif
          dest: /tmp/s3ldap/ssl_certs.ldif

      - name: Update openldap configuration
        command: ldapmodify -Y EXTERNAL  -H ldapi:/// -f /tmp/s3ldap/ssl_certs.ldif
        no_log: true

      - name: Backup original slapd file
        copy:
          src:  /etc/sysconfig/slapd
          dest: /etc/sysconfig/slapd.bak
          backup: yes
          remote_src: yes

      - name: Add ssl & non-ssl ldap URIs
        command: sed -i "s/^SLAPD_URLS=.*/SLAPD_URLS={{ldap_url}}/" /etc/sysconfig/slapd
        no_log: true

      - name: Setup ssl config for ldap client tools
        copy:
          src: files/ldap/ssl/ldap.conf
          dest: /etc/openldap/ldap.conf
          backup: yes

      - name: Delete temp directory
        file:
          name: /tmp/s3ldap
          state: absent

      - name: restart slapd
        service:
          name: slapd
          state: restarted
          enabled: yes

  # handlers:
  #     - name: restart ntpd
  #       service:
  #         name: ntpd
  #         state: restarted
