rpm_package:
  before_script:
    - yum install rpm-build createrepo -y
  script:
    - sh ./rpms/buildrpm.sh
    
cli_rpm_package:
  before_script:
    - yum install rpm-build createrepo -y
  script:
    - sh ./cli/buildrpm.sh
