#!/bin/sh

set -euE

trap trap_handler ERR

SCRIPT_PATH=$(readlink -f "$0")
BASEDIR=$(dirname "$SCRIPT_PATH")
. $BASEDIR/shutdown

function trap_handler {
  echo "For detailed error logs, please see: $LOG_FILE"
}

# Prepare shutdown


# Shutdown HA


# Power-off sequence
shutdown_node
shutdown_controller
