#!/bin/sh
set -eu

function stop_rabbitmq_cluster {
    #salt "*" cmd.run "rabbitmqctl stop_app"
    salt "*" state.apply components.rabbitmq.teardown
}

function stop_services {
    echo "Stopping lnet on both nodes"
    salt "*" service.stop lnet
}

function backup_files {
    bkp_file_list=(
        "/etc/multipath/bindings"
        "/etc/multipath.conf"
    )
    for file in "${bkp_file_list[@]}"; do cp $file $file.bak done
}

function boxing_flag {
    timestamp=$(date "+%Y.%m.%d-%H.%M.%S")
    file_name="/opt/seagate/eos-prvsnr/generated_config/boxing"
    touch $file_name.$timestamp
}
