#!/bin/sh
# Functions in this file address following:
#   1. Stop rabbitmq cluster, if running
#   2. Ref: Stop and restart a RabbitMQ cluster, RMQ clustering 
#   3. Ensure Lnet service is stopped 
#   4. Collect system-wide support bundle using CSM CLI interface
#   5. Backup files 
#       a. /etc/multipath/bindings 
#       b. /etc/multipath.conf 
#   6. Unmount /var/mero and SWAP? (This should be ideally taken care of by OS shutdown)
#   7. Cleanup /tmp 
#   8. Create unboxing user.
#   9. Create boxing flag file on primary node:
#       /opt/seagate/eos-prvsnr/generated_config/boxed
#       Creating file on only one node ensures that the unboxing is executed only on primary node.
set -euE

export LOG_FILE="${LOG_FILE:-/var/log/seagate/provisioner/boxing_prov_tasks.log}"
mkdir -p $(dirname "${LOG_FILE}")
truncate -s 0 ${LOG_FILE}

function trap_handler {
    echo "***** ERROR! *****"
    echo "For detailed error logs, please see: $LOG_FILE"
    echo "******************"
}
trap trap_handler ERR

function stop_rabbitmq_cluster {
    echo "INFO: Removing RabbitMQ from both nodes." | tee -a ${LOG_FILE}
    
    salt "*" state.apply components.misc_pkgs.rabbitmq.teardown || (
        echo "ERROR: Remove RabbitMQ from both nodes failed." | tee -a ${LOG_FILE}
    )

    echo "INFO: Removed RabbitMQ from both nodes." | tee -a ${LOG_FILE}
}

function stop_services {
    echo "INFO: Stop LNET from both nodes if active." | tee -a ${LOG_FILE}

    echo "INFO: Stopping lnet on both nodes" | tee -a ${LOG_FILE}
    salt "*" service.stop lnet || (echo "ERROR: Failed to stop LNET from both nodes." | tee -a ${LOG_FILE})

    echo "INFO: Stopped LNET from both nodes if active." | tee -a ${LOG_FILE}
}

function backup_files {
    echo "INFO: Backing up files on both nodes." | tee -a ${LOG_FILE}

    bkp_file_list=(
        "/etc/multipath/bindings"
        "/etc/multipath.conf"
    )
    for file in "${bkp_file_list[@]}"; do
        cp $file $file.bak
    done

    echo "INFO: Backed up files on both nodes." | tee -a ${LOG_FILE}
}

function create_unboxing_user {
    if ! command -v mkpasswd >/dev/null ; then
        # Install required package if missing
        yum install -y expect >/dev/null
    fi
    
    SECRET=$(mkpasswd -l 10 -d 3 -c 3 -C 3 -s 0)
    useradd --base-dir /tmp --inactive 2 --groups sys --shell /usr/bin/bash  --no-create-home --password $(openssl passwd -1 ${SECRET}) cortxub
    passwd -e cortxub
    
    echo "**********************************************************" 2>&1 | tee -a ${LOG_FILE}
    echo "NOTE: Store this information for unboxing."
    echo "**********************************************************" 2>&1 | tee -a ${LOG_FILE}
    
    echo "System MAC: $(cat /sys/class/net/eno1/address)" 2>&1 | tee -a ${LOG_FILE}
    echo "USERNAME:   cortxub" 2>&1 | tee -a ${LOG_FILE}
    echo "PASSWORD:   ${SECRET}" 2>&1 | tee -a ${LOG_FILE}
 
    echo "**********************************************************" 2>&1 | tee -a ${LOG_FILE}
    echo "NOTE: Password expires on first login." 2>&1 | tee -a ${LOG_FILE}
    echo "**********************************************************" 2>&1 | tee -a ${LOG_FILE}
}

function boxing_flag {
    #Flag file is created only on primary node,
    # as this helps to ensure unboxing is executed only on primary node.
    echo "INFO: Creating flag file on primary node." | tee -a ${LOG_FILE}

    local file_name="/opt/seagate/cortx/provisioner/generated_config/boxed"
    
    if [ ! -f $file_name ]
    then
        timestamp=$(date "+%Y.%m.%d-%H.%M.%S")
        mkdir -p $(dirname "$file_name")
        echo $timestamp > $file_name
    fi

    echo "INFO: Created flag file on primary node." | tee -a ${LOG_FILE}
}
