#!/bin/bash
#
# Copyright (c) 2020 Seagate Technology LLC and/or its Affiliates
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published
# by the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU Affero General Public License for more details.
# You should have received a copy of the GNU Affero General Public License
# along with this program. If not, see <https://www.gnu.org/licenses/>.
# For any questions about this software or licensing,
# please email opensource@seagate.com or cortx-questions@seagate.com.
#

set -euE

function lr_serial_number {
    if [[ $# -eq 0 ]]; then
        if [[ -f /opt/seagate/lr-serial-number ]]; then
            echo "Lyve Rack r1 Serial Number -  $(cat /opt/seagate/lr-serial-number)"
        else
            echo "Lyve Rack r1 Serial Number does not exist"
            exit 21
        fi
    else
        if [[ -f /opt/seagate/lr-serial-number ]]; then
            echo "Lyve Rack r1 Serial Number already set."
            exit 0
        else
            if [[ $(/usr/bin/provisioner --version > /dev/null 2>&1) ]]; then
                /usr/bin/provisioner pillar_set cluster/lr-serial-number $1
            fi
            echo $1 > /opt/seagate/lr-serial-number
            chmod 0644 /opt/seagate/lr-serial-number
            chattr +i /opt/seagate/lr-serial-number
            echo "INFO: Lyve Rack r1 serial number can be found at /opt/seagate/lr-serial-number"
        fi
    fi
}

lr_serial_number $@
