apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: halo
  name: manager
  labels:
    app: manager
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: manager
  template:
    metadata:
      labels:
        app: manager
    spec:
      containers:
      - name: busybox
        image: busybox
        imagePullPolicy: IfNotPresent
        args:
        - -c
        - sleep infinity;
        command:
        - /bin/sh
