#!/bin/bash
set -e;
# Log Levels:
DEBUG=1
INFO=2
WARNING=3
ERROR=4
FATAL=5
DEFAULT_LOG_LEVEL=${DEFAULT_LOG_LEVEL:-$INFO}

function log {
    LEVEL=$1; shift
    LOG_LEVEL=${LOG_LEVEL:-$DEFAULT_LOG_LEVEL}
    [[ $LEVEL -lt $LOG_LEVEL ]] && return

    echo "log: $*"
}

function show_usage {
    echo -e "usage: $(basename $0) [-f SOLUTION-CONFIG] [-l LOG-LEVEL][-c CORTX-CONFIG-URL] [-o] [-d] [-v]"
    echo -e "Where:"
    echo -e "..."
    echo -e " SOLUTION-CONFIG : Solution-Config directory containing -\
                                config.yaml, cluster.yaml and secrets.yaml"
    echo -e "                   (Default: /etc/cortx/solution)"
    echo -e " LOG-LEVEL       : Log Level (Default: 2)"
    echo -e "                   Supported log levels:"
    echo -e "                   DEBUG=1, INFO=2, WARNING=3, ERROR=4, FATAL=5"
    echo -e " CORTX-CONFIG-URL: URL of CORTX Configuration"
    echo -e "                   (Default is yaml:///etc/cortx/cluster.conf)"
    echo -e " FORCE OVER-RIDE : Force provisioning even after CORTX configuration."
    echo -e " ENABLE DEBUG    : Enable Debugging CORTX Deployment (Default: False)"
    echo -e " VALIDATE CONFIG : Validate constore and configmap config."
    exit 1
}

function validate_config {
    local config=$1
    if [ ! -f $config ]; then
        echo -e "ERROR: Config file $config not found, Provide correct config path."
        exit 1
    fi
}

function yaml_config {
    local config=$1
    echo "yaml://$config"
}

function conf_get {
    URL=$1; key=$2
    val=$(conf $URL get $key)
    val=$(echo $val | tr -d "["\" | tr -d "\"]")
    echo $val
}

# Constants
DEBUG_FLAG=false
SOLUTION_CONFIG="/etc/cortx/solution"
CORTX_CONFSTORE="yaml:///etc/cortx/cluster.conf"
RELEASE_INFO="yaml:///opt/seagate/cortx/RELEASE.INFO"

while [ $# -gt 0 ];  do
    case $1 in
    -l )
        shift 1
        LOG_LEVEL=$1
        ;;
    -n )
        shift 1
        NODE_ID=$1
        ;;
    -d )
        DEBUG_FLAG=true
        ;;
    -f )
        shift 1
        SOLUTION_CONFIG=$1
        ;;
    -c )
        shift 1
        CORTX_CONFSTORE=$1
        ;;
    -o )
       FORCE_PROVISIONING="-o"
       ;;
    -h )
        show_usage
        ;;
    -v )
        VALIDATE_CONF="-v"
        ;;
    * )
        echo -e "Invalid argument provided : $1"
        show_usage
        exit 1
        ;;
    esac
    shift 1
done

# path for solution-config cluster.yaml and config.yaml files
CONFIG_INFO="$SOLUTION_CONFIG/config.yaml"
validate_config $CONFIG_INFO
CLUSTER_INFO="$SOLUTION_CONFIG/cluster.yaml"
validate_config $CLUSTER_INFO

export PATH=$PATH:/opt/seagate/provisioner/bin

node_id=`cat /etc/machine-id`
cluster_id=$(conf_get $(yaml_config $CLUSTER_INFO) "cluster>id")
log $INFO "Starting provisioning on node $node_id which is part of cluster $cluster_id."

deploy=false
upgrade=false
# Check current image version
CONFSTOR_FILE=$(awk -F:// '{print $2}' <<< $CORTX_CONFSTORE)
# check if confstore file is empty or not present
if [ ! -s "$CONFSTOR_FILE" ]; then
    log $INFO "$CORTX_CONFSTORE file not found or file is empty"
    log $INFO "deployment set to true"
    deployment=true
else
    current_full_ver=$(conf_get $CORTX_CONFSTORE "cortx>common>release>version")
    # if current version is not available in confstore
    if [ $current_full_ver = "[null]" ]; then
        deployment=true
    else
        # Below can be used when subversioning is considered.
        #current_primary_ver=$(awk -F. '{print $1 "." $2 "." $3}' <<< $current_full_ver)
        current_ver=$(awk -F. '{print $4}' <<< $current_full_ver)
    fi
fi

image_full_ver=$(sed -e 's/[][]//g' -e 's/"//g' <<< $(conf_get $RELEASE_INFO "VERSION"))
# Below can be used when subversioning is considered.
#image_primary_ver=$(awk -F- '{print $1}' <<<  $image_full_ver )
image_ver=$(awk -F- '{print $2}' <<<  $image_full_ver)

if [ $current_ver -eq $image_ver ]; then
    if [ ! -z $FORCE_PROVISIONING ]; then
        deploy=true
    else
        return 0
    fi
elif [ $current_ver -gt $image_ver ]; then
    log $ERROR " Current version:$current_full_ver of cortx-all is greater than input image version:$image_full_ver"
    exit 1
else
    deploy=false
    upgrade=true
fi

# Apply Cluster Config
log $INFO "cortx_setup config apply -f $(yaml_config $CLUSTER_INFO) -c '$CORTX_CONFSTORE' $FORCE_PROVISIONING"
cortx_setup config apply -f $(yaml_config $CLUSTER_INFO) -c "$CORTX_CONFSTORE" $FORCE_PROVISIONING;

# Apply Common Config
log $INFO "cortx_setup config apply -f $(yaml_config $CONFIG_INFO) -c '$CORTX_CONFSTORE' $FORCE_PROVISIONING"
cortx_setup config apply -f $(yaml_config $CONFIG_INFO) -c "$CORTX_CONFSTORE" $FORCE_PROVISIONING;

# Validate config
if ! [ -z $VALIDATE_CONF ];
then
    log $INFO "cortx_setup config validate -f $(yaml_config $CLUSTER_INFO) -c '$CORTX_CONFSTORE'"
    cortx_setup config validate -f $(yaml_config $CLUSTER_INFO) -c "$CORTX_CONFSTORE" || exit 1
    log $INFO "cortx_setup config validate -f $(yaml_config $CONFIG_INFO) -c '$CORTX_CONFSTORE'"
    cortx_setup config validate -f $(yaml_config $CONFIG_INFO) -c "$CORTX_CONFSTORE" || exit 1
fi

if [[ $deploy = true && $upgrade = false ]]; then
    # Bootstrap Cluster
    log $INFO "cortx_setup cluster bootstrap -c '$CORTX_CONFSTORE' $FORCE_PROVISIONING"
    cortx_setup cluster bootstrap -c "$CORTX_CONFSTORE" $FORCE_PROVISIONING;
elif [[ $deploy = false && $upgrade = true ]]; then
    log $INFO "cortx_setup cluster upgrade -c '$CORTX_CONFSTORE' $FORCE_PROVISIONING"
    cortx_setup cluster upgrade -c "$CORTX_CONFSTORE" $FORCE_PROVISIONING;
fi

# Check if debugging is enabled
if [ $DEBUG_FLAG = true ]; then
    log $INFO "cortx_setup DEBUG enabled...";
    sleep infinity;
fi
