apiVersion: v1
kind: ConfigMap
metadata:
  name: cortx-config
data:
  cluster.yaml: |
    cluster:
      name: cortx-cluster
      logical_node_class:
      - name: storage_node
        components:
        - name: motr             # (motr_setup --services=io)
          services: 
          - io
        - name: hare             # (hare_setup --services=all)
        - name: s3
          services:              # (s3_setup --services=io,auth,bg_consumer)
          - io
          - auth
          - bg_consumer
        - name: utils
          services:              # (utils_setup --services=message_bus)
          - message_bus
        storage:
        - name: cvg-01
          metadata_devices:
          - /dev/sda
          data_devices:
          - /dev/sdb
          - /dev/sdc
        - name: cvg-02
          metadata_devices:
          - /dev/sdx
          data_devices:
          - /dev/sdy
          - /dev/sdz
      - name: control_node
        components: 
        - name: csm             # (csm_setup --services=agent)
          services:
          - agent
        - name: motr            # (motr_setup --services=fsm)
          services:
          - fsm
        - name: s3              # (s3_setup --services=bg_producer)
          services:
          - bg_producer
      storage_sets:
      - name: storage-set-1
        durability:
          sns: 8+7+0
          dix: 1+7+0
      logical_nodes:
      - name: pod-1
        host_name: pod-1.colo.seagate.com
        class: storage_node
      - name: pod-2
        host_name: pod-2.colo.seagate.com
        class: control_node
      - name: pod-*          # TBD: Future Optimization
        host_name: pod-*.colo.seagate.com
        class: storage_node
      index: 0-14
  config.yaml: |
    cortx:
      external_services:
        kafka:
          endpoints:
            - kafka-server1.cortx-cluster.lyve-cloud.com
            - kafka-server2.cortx-cluster.lyve-cloud.com
          user: admin
          secret: gAAAAABf
        openldap:
          endpoints:
            - oldap-server1.cortx-cluster.lyve-cloud.com
        consul:
          endpoints:
            - consul-server1.cortx-cluster.lyve-cloud.com
      common:
        product_release: LC
        environment_type: K8
        storage:
          shared: /share/var/data/cortx
          log: /share/var/log/cortx
          misc: /var/data/cortx
          config: /etc/cortx
      utils:
        message_bus_backend: kafka
      s3:
        service_instances: 11
        io_max_units: 32
        ports:
          iam:
            - 9443/https
            - 9080/https
          data:
            - 80/http
            - 443/https
          background:
            - 81111/http
            - 82222/https
      motr:
        client_instances: 2
      hare:
        ports:
          hax: 
            - 28000/tcp
      csm:
        ports:
      agent:
        - 8080/http
        - 8081/https
