#
# Copyright (c) 2020 Seagate Technology LLC and/or its Affiliates
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published
# by the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU Affero General Public License for more details.
# You should have received a copy of the GNU Affero General Public License
# along with this program. If not, see <https://www.gnu.org/licenses/>.
# For any questions about this software or licensing,
# please email opensource@seagate.com or cortx-questions@seagate.com.
#

---
- scm:
    name: project-scm
    scm:
      - git:
         name: origin
         url: 'https://github.com/{github_org}/cortx-prvsnr'
         # credentials-id: '{credentials_id}' XXX
         branches:
          # 2nd brackets are to escape the 1st ones (not a template),
          # the result should be ${sha1}
          - '${{sha1}}'
         skip-tag: true
         wipe-workspace: true
         clean: true
         refspec: +refs/pull/*:refs/remotes/origin/pr/*

- parameter:
    name: commit-id-build-parameter
    parameters:
      - string:
          name: sha1
          default: '{defaut_commit_id}'
          description: 'Commit id to build or refname (e.g. origin/pr/1234/head, origin/pr/1234/merge)'

- parameter:
    name: testing-topics-parameter
    parameters:
      - validating-string:
          name: topic
          default: '{default_topic}'
          description: 'Space separated testing topics. Options: {topic_regex}'
          regex: '{topic_regex}'
          msg: Value validation failed

- parameter:
    name: testing-level-parameter
    parameters:
      - validating-string:
          name: level
          default: '{default_level}'
          description: 'A testing level. Available options: {level_regex}'
          regex: '{level_regex}'
          msg: Value validation failed

- trigger:
    name: ghprb-trigger
    triggers:
      - github-pull-request:
          cron: '{ghprb_cron}'  # TODO actually it doesn't work if hooks are used
          # github-hooks: true
          permit-all: false
          white-list: '{obj:ghprb_user_whitelist}'
          org-list: '{obj:ghprb_org_whitelist}'
          allow-whitelist-orgs-as-admins: '{obj:ghprb_allow_white_org_as_admins}'
          admin-list: '{obj:ghprb_admins}'
          white-list-target-branches: '{obj:ghprb_target_branches}'
          trigger-phrase: '{ghprb_trigger_prefix}\s+test\s+{ghprb_trigger_pattern}\s+please'
          only-trigger-phrase: '{ghprb_only_trigger_phrase}'
          status-context: '{ghprb_status_context}'
          cancel-builds-on-update: true  # TODO works only with JJB version >2.0.0
