@startuml

note "CORTX Lifecycle \nas Managed by Provisioner" as N1
' don't use "title", it creates bad file names in VS Code

hide empty description
' scale 600 width

[*] --> Factory_Provisioned : Initial Provisioning
Factory_Provisioned --> Boxed : Boxing
Boxed --> Unboxed : Un-Boxing

state Operational {
    Normal --> Degraded : Node Death / \nFail-Over
    Degraded --> Normal : Node Replacement / \nFail-Back

    Normal --> SW_Update : Update Started
    SW_Update --> Normal : Update Completed
}

Unboxed --> Normal : On-Boarding\n(by CSM)

@enduml