cortx:
  external:
    kafka:                      # Service endpoint (HA enabled)
      endpoints:
      - tcp://kafka-server.cortx-cluster.lyve-cloud.com:9092
      admin: admin
      secret: gAAAAABf
    openldap:
      endpoints:                # Service endpoint (HA enabled)
      - ldap://oldap-server.cortx-cluster.lyve-cloud.com:389
      - ssl://oldap-server.cortx-cluster.lyve-cloud.com:636
      servers:                  # Open ldap servers in the cluster
      - oldap-server1.cortx-cluster.lyve-cloud.com
      - oldap-server2.cortx-cluster.lyve-cloud.com
      - oldap-server3.cortx-cluster.lyve-cloud.com
      admin: admin
      secret: gAAAAABf
      base_dn: dc=seagate,dc=com
    consul:
      endpoints:                # Service endpoint (HA enabled)
      - consul-server1.cortx-cluster.lyve-cloud.com:<port>
      admin: admin
      secret: gAAAAABf
  common:
    product_release: LC
    environment_type: K8
    service:
      admin: admin
      secret: gAAAAABf
    security:
      ssl_certificate: /etc/ssl/stx/stx.pem
      domain_certificate: /etc/ssl/stx/stx.pem
      device_certificate: /etc/ssl/stx/stx.pem
    storage:
      shared: /share
      log: /share/var/log/cortx
      misc: /var/data/cortx
      config: /etc/cortx
  utils:
    message_bus_backend: kafka
  s3:
    iam:
      endpoints:
      - https://s3-iam.seagate.com:9443
    data:
      endpoints:
      - http://s3.seagate.com:80
      - https://s3.seagate.com:443
    service_instances: 11
    io_max_units: 32
    auth_admin: admin
    auth_secret: gAAAAABf
  motr:
    client_instances: 2
    interface_type: tcp
    interface_family: inet
    transport_type: libfab
    ios:
      endpoints:
      - motr://motr-data1.cortx-cluster.lyve-cloud.com:3232
  hare:
    hax:
      endpoints:
      - tcp://hax.seagate.com:28000
  csm:
    auth_admin: admin
    auth_secret: gAAAAABf
    mgmt_admin: cortxadmin
    mgmt_secret: gAAAAABf
    email_address: cortx@seagate.com
    agent:
      endpoints:
      - https://csm.seagate.com:8081
