FROM python:3.6-slim-buster

ARG user=test
ARG group=test
ARG uid=1000
ARG gid=1000

RUN groupadd -g ${gid} ${group}
RUN useradd -c "test user" -d /home/${user} -u ${uid} -g ${gid} -m ${user}

ARG PROJECT_PATH=/tmp/project
COPY python $PROJECT_PATH

# FIXME not the best choice to install that globally
RUN pip3 install ${PROJECT_PATH}[test]

RUN rm -rf $PROJECT_PATH

USER ${user}
