#!/bin/sh
set -eu

SCRIPT_PATH=$(readlink -f "$0")
BASEDIR=$(dirname "$SCRIPT_PATH")
. ${BASEDIR}/config_update

# Update /root/.ssh/config file with hosts
update_ssh_config
update_salt_minion
update_cluster_sls

# # Update RabbitMQ cluster
# salt "eosnode-1" state.apply components.misc_pkgs.rabbitmq
# salt "eosnode-2" state.apply components.misc_pkgs.rabbitmq

# # Update SSPL init
# salt "*" state.apply components.s3server.config
# salt "*" state.apply components.sspl.config
# salt "*" state.apply components.csm.config
