#!/bin/sh
set -eu

usage() {
  echo "Usage: \
  sh build
  
  Options:
  h      Help
  "
}

while getopts ":h" o; do
    case "${o}" in
      h | * )
        usage
        ;;
    esac
done
shift $((OPTIND-1))

# packer validate ./centos_75_1804_vbox.json
# packer build ./centos_75_1804_vbox.json

packer validate ./centos_75_1804_hyperv.json
# packer build ./centos_75_1804_hyperv.json