#!/bin/sh
set -eu
BASEDIR=$(dirname "${BASH_SOURCE}")

usage() {
  echo "Usage: \
  sh build
  
  Options:
  h      Help
  "
}

while getopts ":h" o; do
    case "${o}" in
      h | * )
        usage
        ;;
    esac
done
shift $((OPTIND-1))

# packer validate ${BASEDIR}/centos_75_1804_vbox.json
# packer build ${BASEDIR}/centos_75_1804_vbox.json

# packer validate ${BASEDIR}/centos_75_1804_hyperv.json
# packer build ${BASEDIR}/centos_75_1804_hyperv.json

packer validate ${BASEDIR}/centos_78_2003_hyperv.json
# packer build ${BASEDIR}/centos_78_2003_hyperv.json
