FROM {parent}

# TODO populate .dockerignore
# setup provisioner repo and salt
COPY files /opt/seagate/eos-prvsnr/files/
COPY pillar /opt/seagate/eos-prvsnr/pillar/
COPY srv /opt/seagate/eos-prvsnr/srv/
COPY cli/utils /opt/seagate/eos-prvsnr/cli/utils/
COPY cli/src/setup-provisioner /opt/seagate/eos-prvsnr/cli/src/
RUN sed -i 's/\(systemctl restart\)/#\1/g' /opt/seagate/eos-prvsnr/cli/src/setup-provisioner \
    && cat /opt/seagate/eos-prvsnr/cli/src/setup-provisioner \
    && bash -x /opt/seagate/eos-prvsnr/cli/src/setup-provisioner \
    && rm -rf /var/cache/yum
