FROM {parent}

# TODO populate .dockerignore
COPY cli/src/common_utils/functions.sh /tmp/
RUN bash -xec ". /tmp/functions.sh; install_salt '' '' '' true" \
    && rm -f /tmp/functions.sh \
    && rm -rf /var/cache/yum
