FROM {parent}

# install salt as python package

# we use pip install (not pipenv install) to make that faster
RUN pipenv run pip install install salt==3002.2 \
    && pipenv run salt --version

# set python salt env

# TODO expose SALT_CONFIG as env variable - is it possible for salt?
ENV SALT_BASEDIR=/tmp/salt
ENV SALT_CONFIG=${{SALT_BASEDIR}}/config
ENV SALT_SRV=${{SALT_BASEDIR}}/srv
ENV SALT_FILEROOT=${{SALT_SRV}}/salt
ENV SALT_PILLARROOT=${{SALT_SRV}}/pillar

COPY images/docker/salt/config ${{SALT_CONFIG}}
RUN mkdir -p ${{SALT_CONFIG}} ${{SALT_FILEROOT}} ${{SALT_PILLARROOT}}
