FROM jenkins/inbound-agent

USER root

# docker
RUN apt-get -y update \
    && apt-get -y install apt-transport-https ca-certificates curl gnupg lsb-release \
    && curl -fsSL https://download.docker.com/linux/debian/gpg | gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg \
    && echo \
        "deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/debian \
        $(lsb_release -cs) stable" | tee /etc/apt/sources.list.d/docker.list > /dev/null \
    && apt-get update \
    && apt-get -y install docker-ce docker-ce-cli containerd.io \
    && rm -rf /var/lib/apt/lists/*

RUN usermod -aG docker jenkins

# python
RUN apt-get update && apt-get install -y \
        python3 \
        python3-pip \
        python-setuptools \
    && rm -rf /var/lib/apt/lists/*

# pypi based packages
RUN pip3 install -U \
        pip \
        setuptools

USER jenkins
