@startuml

!pragma teoz true
hide footbox

title "Continious Integration (simplified)"

actor Contributor
actor Maintainer
participant VCS
participant CI

Contributor -> Contributor: Make changes
Contributor -> Contributor: Fix regressions
Contributor -> VCS: Push

VCS -> CI: Hook

CI -> CI: Run tests
CI -> VCS: Update commit status

VCS -> Contributor: Notification
VCS -> Maintainer: Notification

opt if passed only
    Maintainer -> VCS: Merge the request
    VCS -> Contributor: Notification
end opt

@enduml
