#!/bin/bash

set -eu

SCRIPT_PATH=$(readlink -f "$0")
BASEDIR=$(dirname "$SCRIPT_PATH")

. $BASEDIR/common_utils/functions.sh

function usage {
  echo "\
Usage: $0 [options]

Initializes CORTX services either on remote host or locally.

Target host is considered to be an CORTX SaltStack master.

General options:
$base_options_usage
"
}

parse_args '' '' '' '' "$@"

if [[ "$verbosity" -ge 2 ]]; then
    set -x
fi

cmd="$(build_command "$hostspec" "$ssh_config" "$sudo" 2>/dev/null)"

salt_opts=
if [[ "$dry_run" == true ]]; then
    salt_opts="test=True"
fi

# apply states
if [[ "$singlenode" == true ]]; then
    l_info "Applying 'components.post_setup' for srvnode-1 (singlenode)"
    $cmd salt srvnode-1 state.apply components.post_setup $salt_opts
else
    l_info "Applying 'components.post_setup' for srvnode-2"
    $cmd salt srvnode-2 state.apply components.post_setup $salt_opts

    l_info "Applying 'components.post_setup' for srvnode-1"
    $cmd salt srvnode-1 state.apply components.post_setup $salt_opts
fi

l_info "Done"
