#!/bin/bash

set -eu

SCRIPT_PATH=$(readlink -f "$0")
BASEDIR=$(dirname "$SCRIPT_PATH")

. $BASEDIR/functions.sh

function usage {
  echo "\
Usage: $0 [options]

Initializes EOS services either on remote host or locally.

Target host is considered to be an EOS SaltStack master.

General options:
$base_options_usage
"
}

parse_args '' '' '' '' "$@"

cmd="$(build_command "$hostspec" "$ssh_config" "$sudo")"

salt_opts=
if [[ "$dry_run" == true ]]; then
    salt_opts="test=True"
fi

# apply states
if [[ "$singlenode" == true ]]; then
    $cmd salt eosnode-1 state.apply components.post_setup $salt_opts
else
    $cmd salt eosnode-2 state.apply components.post_setup $salt_opts
    $cmd salt eosnode-1 state.apply components.post_setup $salt_opts
fi

echo "Done"
