#!/bin/bash

set -eu

SCRIPT_PATH=$(readlink -f "$0")
BASEDIR=$(dirname "$SCRIPT_PATH")

. $BASEDIR/functions.sh

function usage {
  echo "\
Usage: $0 [options]

Installs EOS stack and configures eos services either on remote host or locally.

Target host is considered to be an EOS SaltStack master.

General options:
$base_options_usage
"
}

parse_args '' '' '' '' "$@"

if [[ "$verbosity" -ge 2 ]]; then
    set -x
fi

cmd="$(build_command "$hostspec" "$ssh_config" "$sudo" 2>/dev/null)"

salt_opts=
if [[ "$dry_run" == true ]]; then
    salt_opts="test=True"
fi

# apply states
if [[ "$singlenode" == true ]]; then
    # TODO use salt orchestration
    for state in system system.storage misc_pkgs.build_ssl_cert_rpms ha.corosync-pacemaker ha.haproxy misc_pkgs.elasticsearch misc_pkgs.kibana misc_pkgs.nodejs misc_pkgs.openldap misc_pkgs.rabbitmq misc_pkgs.statsd eoscore s3server hare sspl csm; do
        l_info "Applying 'components.$state'"
        $cmd salt eosnode-1 state.apply components.$state $salt_opts
    done
else
    # Platform provisioning
    l_info "Platform provisioning"
    for state in system system.storage; do
        l_info "Applying 'components.$state' for both nodes"
        $cmd salt eosnode-[1,2] state.apply components.$state $salt_opts
    done

    # External dependency provisioning
    l_info "External dependency provisioning"
    for state in misc_pkgs.build_ssl_cert_rpms ha.corosync-pacemaker ha.haproxy misc_pkgs.elasticsearch misc_pkgs.kibana misc_pkgs.nodejs misc_pkgs.openldap misc_pkgs.rabbitmq misc_pkgs.statsd; do
        l_info "Applying 'components.$state' for both nodes"
        $cmd salt eosnode-[1,2] state.apply components.$state $salt_opts
    done

    # Execute on eosnode-2 only if cert generation on eosnode-1 succeeds.
    l_info "Applying 'components.misc_pkgs.build_ssl_cert_rpms' for eosnode-1"
    $cmd salt eosnode-1 state.apply components.misc_pkgs.build_ssl_cert_rpms $salt_opts
    l_info "Applying 'components.misc_pkgs.build_ssl_cert_rpms' for eosnode-2"
    $cmd salt eosnode-2 state.apply components.misc_pkgs.build_ssl_cert_rpms $salt_opts

    # IO stack provisioning
    l_info "IO stack provisioning"
    for state in eoscore s3server hare; do
        l_info "Applying 'components.$state' for both nodes"
        $cmd salt eosnode-[1,2] state.apply components.$state $salt_opts
    done

    # Management stack provisioning
    l_info "Management stack provisioning"
    for state in sspl csm; do
        l_info "Applying 'components.$state' for both nodes"
        $cmd salt eosnode-[1,2] state.apply components.$state $salt_opts
    done
fi

l_info "Done"
