#!/usr/bin/env python3
import sys
import tarfile
import os
import argparse

def parse_args():
    parser=argparse.ArgumentParser(description='''Bundle provisioner logs ''')
    parser.add_argument('bundle_id', help='Unique bundle id')
    parser.add_argument('path', help='Path to store the created bundle', nargs='?', default="/var/seagate/eos/support_bundle/")
    args=parser.parse_args()
    return args

def prepare_target_file(args):
    try:
        component="provisioner"
        target_path=os.path.join(args.path, args.bundle_id, component)
        print(target_path)
        os.makedirs(target_path,exist_ok=True)
        target_file=target_path+'/'+component+'_'+args.bundle_id+'.tar.gz'
        return target_file
    except:
        print("ERROR: Unable to create component specific directory!!")
        sys.exit(1)

def make_tarfile(output_filename, source_dir):
    with tarfile.open(output_filename, "w:gz") as tar:
        tar.add(source_dir, arcname=os.path.basename(source_dir))

args=parse_args()
target_file=prepare_target_file(args)
make_tarfile(target_file, '/var/log/provisioner/')