#!/bin/bash

set -eu

SCRIPT_PATH=$(readlink -f "$0")
BASEDIR=$(dirname "$SCRIPT_PATH")

. $BASEDIR/functions.sh

function usage {
  echo "\
Usage: $0 [options] [ees-prvsnr-tag]

Defaults:
 ees-prvsnr-tag: latest tagged

Options:
$base_options_usage
"
}

# TODO update tests
function positional_args_parser {
    set -eu

    if [[ $# -gt 1 ]]; then
        >&2 echo "$0: Only one positional argument is expected, provided: $@"
        exit 2
    fi

    prvsnr_version="${1:-}"
}

parse_args '' '' '' positional_args_parser "$@"

cmd=$(build_command)

INSTALLDIR="/opt/seagate/ees-prvsnr"
EES_PRVSNR_REPO_API_TAGS='http://gitlab.mero.colo.seagate.com/api/v4/projects/eos%2Fprovisioner%2Fees-prvsnr/repository/tags?order_by=updated&sort=desc'

# TODO replace with eos-provisioner.rpm installation
if [ ! -d "$INSTALLDIR" ]; then
    if [ -z "$prvsnr_version" ]; then
        _tags=$(curl "$EES_PRVSNR_REPO_API_TAGS")
        prvsnr_version=$(echo "$_tags" | tr ',' '\n' | sed -n 's/.*"name":"\(.\+\)".*/\1/p' | head -n1)
    fi

    if [ -z "$prvsnr_version" ]; then
        >&2 echo 'Version of the provisioner repo is unknown'
        exit 1
    fi

    mkdir -p "$INSTALLDIR"
    pushd "$INSTALLDIR"
        curl "http://gitlab.mero.colo.seagate.com/eos/provisioner/ees-prvsnr/-/archive/${prvsnr_version}/${prvsnr_version}.tar.gz" | tar xzf - --strip-components=1
    popd
fi

pushd "$INSTALLDIR"

    # config custom yum repos
    $cmd rm -rf /var/cache/yum
    $cmd rm -rf /etc/yum.repos.d
    $cmd cp -R files/etc/yum.repos.d /etc

    # install salt
    $cmd yum install -y salt-minion

    # re-config and restart salt
    $cmd mv -f /etc/salt/minion /etc/salt/minion.org
    $cmd cp files/etc/salt/minion /etc/salt/minion
    $cmd systemctl restart salt-minion

    # ensure it works and log the version
    $cmd salt-call --version

popd

echo "Done"
