#!/bin/bash

set -euE

function trap_handler {
  echo "For detailed error logs, please see: $LOG_FILE"
}

trap trap_handler ERR

BASEDIR=$(dirname "${BASH_SOURCE}")

. $BASEDIR/functions.sh

export LOG_FILE="${LOG_FILE:-/var/log/seagate/provisioner/sos-generate.log}"
mkdir -p $(dirname "${LOG_FILE}")
truncate -s 0 ${LOG_FILE}

BUNDLE_ID=
DIR_PATH=


parse_arguments() {
    set -eu

    if [[ $# -gt 2 ]]; then
        l_error "$0: Only 2 positional arguments are expected, provided: $@"
        exit 2
    fi

    BUNDLE_ID="$1"
    DIR_PATH="$2"

}

if [[ -z "$(rpm -qa | grep sos)" ]]; then
    l_error "SOS rpm not installed."
    exit 1
fi

if [[ -z "$(grep -F "Red Hat Enterprise Linux" /etc/redhat-release)" ]]; then
    l_error "We need RHEL OS to run this script."
    exit 1
fi

parse_arguments "$@"

sosreport_path=$DIR_PATH/os/os_$BUNDLE_ID.tar.gz
mkdir -p $DIR_PATH/os
l_info "Generating SOS logs"
sosreport --all-logs --case-id=$BUNDLE_ID --debug --batch 2>&1|tee ${LOG_FILE}  #sosreport -k rpm.rpmva=off

sos_report_file="$(ls -Art /var/tmp/ | grep ^sosreport.*tar.xz$ | tail -n 1)"
if [[ -z ${sos_report_file} ]]; then
    l_error "No SOS report generated."
    exit 1
fi
 
mv /var/tmp/${sos_report_file} ${sosreport_path}

l_info "SOS report generated can be found at $sosreport_path"

l_info "DONE"

