#!/bin/bash

set -eu

SCRIPT_PATH=$(readlink -f "$0")
BASEDIR=$(dirname "$SCRIPT_PATH")

. $BASEDIR/functions.sh

restart=false

function usage {
  echo "\
Usage: $0 [options]

Starts all EOS services either on remote host or locally.

Restart EOS services if '--restart' flag is explicitly
specified.

Target host is considered to be an EOS SaltStack master.

General options:
$base_options_usage

Options:
    -R,  --restart              restart all services
"
}

# TODO tests
function options_parser {
    case "$1" in
        -R|--restart)
            restart=true
            ;;
        *)
            >&2 echo "Unknown option: $1"
            exit 5
    esac
}

parse_args 'R' 'restart' options_parser '' "$@"

cmd="$(build_command "$hostspec" "$ssh_config" "$sudo")"

salt_opts=
if [[ "$dry_run" == true ]]; then
    salt_opts="test=True"
fi

target_minions='*'
if [[ -n "$hostspec" ]]; then
    target_minions="'*'"
fi

# apply states
if [[ "$restart" == true ]]; then
    $cmd salt "$target_minions" state.apply components.stop $salt_opts
    $cmd salt "$target_minions" state.apply components.start $salt_opts
else
    $cmd salt "$target_minions" state.apply components.start $salt_opts
fi

echo "Done"
