#!/bin/sh

set -eu

SCRIPT_PATH=$(readlink -f "$0")
BASEDIR=$(dirname "$SCRIPT_PATH")

. $BASEDIR/functions.sh

function usage {
  echo "\
Usage: $0 [options]

Stop all EOS services either on remote host or locally.

Target host is considered to be an EOS SaltStack master.

General options:
$base_options_usage
"
}

parse_args '' '' '' '' "$@"

cmd="$(build_command "$hostspec" "$ssh_config" "$sudo")"

salt_opts=
if [[ "$dry_run" == true ]]; then
    salt_opts="test=True"
fi

target_minions='*'
if [[ -n "$hostspec" ]]; then
    target_minions="'*'"
fi

# apply states
$cmd salt "$target_minions" state.apply components.stop $salt_opts

echo "Done"
