#!/bin/bash
# vim: ft=bash

script_dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
project_dir="$(realpath "$script_dir/../..")"

remark_image_name=seagate/remark-lint 

docker build -t "$remark_image_name" -f "${project_dir}/images/docker/Dockerfile.remark" "${script_dir}"

docker run -it -u $(id -u):$(id -g) -v "$PWD:$PWD" -w "$PWD" "$remark_image_name" "$@"
