#!/bin/sh

set -eu

export LOG_FILE="${LOG_FILE:-/var/log/seagate/provisioner/utils.log}"
truncate -s 0 ${LOG_FILE}

function get_pillar_data {
    local l_key=${1:-}

    if [[ $# -gt 1 ]]; then
        echo "[ERROR] $0: Only one positional argument is expected, provided: $@" | tee -a ${LOG_FILE}
        exit 2
    elif [[ $# -eq 0 ]]; then
        echo "[ERROR] $0: This function expects an argument." | tee -a ${LOG_FILE}
        exit 1
    fi

    local l_val=$(salt-call pillar.get ${l_key} --output=newline_values_only)
    echo ${l_val}
}
